activation: lrelu
arch_option: 0
backbone: clip_vitl16_384
block_depth: 0
ckpt_path: /Users/harshithkethavath/Library/Mobile Documents/com~apple~CloudDocs/University
  of Georgia/Dr. Weiming Hu/2026_CloudPrompts/models/fss_l16.ckpt
crop_size: 480
features: 256
ignore_index: 255
lr: 0.0001
num_classes: 7
weight_decay: 0.01
