"""
Object-Oriented wrapper around different WeatherMind models.
"""

from __future__ import annotations
from typing import Any, Callable, Dict, Optional, Iterable
from pathlib import Path

import torch
from PIL import Image
from transformers import (
    AutoProcessor,
    Qwen2VLForConditionalGeneration,
    AutoTokenizer,
    AutoModelForCausalLM,
    AutoModelForImageTextToText,
    Gemma3ForConditionalGeneration,
)

import re
import pandas as pd
import numpy as np

from transformers.utils import logging as hf_logging

hf_logging.set_verbosity_error()
hf_logging.disable_progress_bar()


#############################################
############### Configuration ###############
#############################################

SUPPORTED_MODEL_NAMES = ["QWEN", "SMOLVLM", "MOONDREAM", "GEMMA"]
DEFAULT_MODEL_NAME = "QWEN"
DEFAULT_TEMPLATE = """
You are WeatherMind, a vision-language model that looks at outdoor image and
describes the weather and return response as JSON.
""".strip()


#############################################
################# Models ####################
#############################################

class BaseWeatherModel:
    """
    Base class for all WeatherMind models.

    Each concrete model must implement __call__(self, input_data: Any, template: str | None = None) -> Any
    so that it can be used as a callable.
    """

    def __call__(self, input_data: Any, template: Optional[str] = None) -> Any:
        raise NotImplementedError("Subclasses must implement __call__")


###############################
############ QWEN #############
###############################

class QwenWeatherModel(BaseWeatherModel):
    """
    Concrete implementation of a Qwen2-VL model for WeatherMind.

    It:
      - Loads the Qwen2-VL-2B-Instruct vision-language model.
      - Accepts an image (or path) plus a text template/question.
      - Returns the raw text generated by the model.
    """

    def __init__(
        self,
        model_id: str = "Qwen/Qwen2-VL-2B-Instruct",
        max_new_tokens: int = 1000,
        temperature: float = 0.7,
        top_p: float = 0.9,
    ) -> None:
        self.model_id = model_id
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.top_p = top_p

        self.device = torch.device("cpu")

        self.processor = AutoProcessor.from_pretrained(self.model_id)
        self.model = Qwen2VLForConditionalGeneration.from_pretrained(
            self.model_id,
            torch_dtype=torch.float32,
        ).to(self.device)

    def __call__(self, input_data: Any, template: Optional[str] = None) -> str:
        """
        Run Qwen2-VL on the given image + template and return the raw text output.

        Args:
            input_data: Image or path to image (PIL.Image.Image, str, or Path).
            template: Instruction/question about the image.
                      If None, uses DEFAULT_TEMPLATE.
        """
        image = _load_image(input_data)

        prompt = template or DEFAULT_TEMPLATE

        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {"type": "image", "image": image},
                ],
            }
        ]

        text = self.processor.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )

        inputs = self.processor(
            text=[text],
            images=[image],
            return_tensors="pt",
        ).to(self.device)

        with torch.inference_mode():
            generated_ids = self.model.generate(
                **inputs,
                max_new_tokens=self.max_new_tokens,
                do_sample=True,
                temperature=self.temperature,
                top_p=self.top_p,
            )

        output_ids = generated_ids[:, inputs["input_ids"].shape[1] :]

        text_out = self.processor.batch_decode(
            output_ids,
            skip_special_tokens=True,
        )[0]

        return text_out.strip()


###############################
########## SMOLVLM ############
###############################

class SmolVLM2WeatherModel(BaseWeatherModel):
    """
    Vision-language WeatherMind model using SmolVLM2-2.2B-Instruct.

    - Takes an image (or path) + a text question/prompt.
    - Returns the raw text answer from SmolVLM2.
    """

    def __init__(
        self,
        model_id: str = "HuggingFaceTB/SmolVLM2-2.2B-Instruct",
        max_new_tokens: int = 1000,
        temperature: float = 0.7,
        top_p: float = 0.9,
    ) -> None:
        self.model_id = model_id
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.top_p = top_p

        self.device = torch.device("cpu")

        self.processor = AutoProcessor.from_pretrained(self.model_id)
        self.model = AutoModelForImageTextToText.from_pretrained(
            self.model_id,
            torch_dtype=torch.float32,
        ).to(self.device)

    def __call__(self, input_data: Any, template: Optional[str] = None) -> str:
        """
        Run SmolVLM2 on (image, question) and return the text answer.

        Args:
            input_data: Image or path to image (PIL.Image.Image, str, or Path).
            template: Instruction/question about the image.
                      If None, uses DEFAULT_TEMPLATE.
        """
        image = _load_image(input_data)

        prompt = template or DEFAULT_TEMPLATE

        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": image},
                    {"type": "text", "text": prompt},
                ],
            }
        ]

        inputs = self.processor.apply_chat_template(
            messages,
            add_generation_prompt=True,
            tokenize=True,
            return_dict=True,
            return_tensors="pt",
        ).to(self.device)

        with torch.inference_mode():
            generated_ids = self.model.generate(
                **inputs,
                max_new_tokens=self.max_new_tokens,
                do_sample=True,
                temperature=self.temperature,
                top_p=self.top_p,
            )

        generated_texts = self.processor.batch_decode(
            generated_ids,
            skip_special_tokens=True,
        )
        return generated_texts[0].strip()


###############################
######### MOONDREAM ###########
###############################

class Moondream2WeatherModel(BaseWeatherModel):
    """
    Vision-language WeatherMind model using vikhyatk/moondream2.

    - Takes an image (or path) + a text question/prompt.
    - Uses the model's built-in `query(image, question)` API.
    - Returns the raw text answer.
    """

    def __init__(
        self,
        model_id: str = "vikhyatk/moondream2",
        revision: str = "2025-06-21",
    ) -> None:
        self.model_id = model_id
        self.revision = revision

        try:
            import torch.backends.mps as mps_backend

            if hasattr(mps_backend, "is_available"):
                mps_backend.is_available = lambda: False
            if hasattr(mps_backend, "is_built"):
                mps_backend.is_built = lambda: False
        except Exception:
            pass

        self.device = torch.device("cpu")

        self.model = AutoModelForCausalLM.from_pretrained(
            self.model_id,
            revision=self.revision,
            trust_remote_code=True,
        )


    def __call__(self, input_data: Any, template: Optional[str] = None) -> str:
        """
        Run Moondream2 on (image, question) and return the answer string.
        """
        image = _load_image(input_data)

        question = template or DEFAULT_TEMPLATE

        result = self.model.query(image, question)

        answer = result.get("answer", "")
        return str(answer).strip()


###############################
########### GEMMA #############
###############################

class Gemma3WeatherModel(BaseWeatherModel):
    """
    WeatherMind wrapper for Gemma 3 4B IT (multimodal).

    Uses:
        model_id = "google/gemma-3-4b-it"
        AutoProcessor.apply_chat_template for (image + question) -> answer.
    """

    def __init__(
        self,
        model_id: str = "google/gemma-3-4b-it",
        max_new_tokens: int = 500,
        temperature: float = 0.7,
        top_p: float = 0.9,
    ):
        self.model_id = model_id
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.top_p = top_p

        if torch.backends.mps.is_available():
            self.device = torch.device("mps")
            dtype = torch.bfloat16
        else:
            self.device = torch.device("cpu")
            dtype = torch.float32

        self.processor = AutoProcessor.from_pretrained(self.model_id)

        self.model = Gemma3ForConditionalGeneration.from_pretrained(
            self.model_id,
            torch_dtype=dtype,
        ).to(self.device)
        self.model.eval()

    def __call__(self, input_data: Any, template: Optional[str] = None) -> str:
        """
        Args:
            input_data: image path or PIL.Image.Image
            template: the *question* about the image (string)
        Returns:
            Plain text answer from Gemma 3.
        """
        if template is None:
            template = DEFAULT_TEMPLATE

        image = _load_image(input_data)

        messages = [
            {
                "role": "system",
                "content": [
                    {
                        "type": "text",
                        "text": "You are WeatherMind, a vision-language assistant for understanding outdoor sky/weather images.",
                    }
                ],
            },
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": image},
                    {"type": "text", "text": template},
                ],
            },
        ]

        inputs = self.processor.apply_chat_template(
            messages,
            tokenize=True,
            return_dict=True,
            return_tensors="pt",
            add_generation_prompt=True,
        ).to(self.device, dtype=self.model.dtype)

        input_len = inputs["input_ids"].shape[-1]

        with torch.inference_mode():
            generation = self.model.generate(
                **inputs,
                max_new_tokens=self.max_new_tokens,
                do_sample=True,
                temperature=self.temperature,
                top_p=self.top_p,
            )
            generation = generation[0, input_len:]

        decoded = self.processor.decode(
            generation,
            skip_special_tokens=True,
            clean_up_tokenization_spaces=True,
        )

        return decoded.strip()


#############################################
############## Model Registry ###############
#############################################

MODEL_REGISTRY: Dict[str, Callable[[], BaseWeatherModel]] = {
    "QWEN": QwenWeatherModel,
    "SMOLVLM": SmolVLM2WeatherModel,
    "MOONDREAM": Moondream2WeatherModel,
    "GEMMA": Gemma3WeatherModel,
}


#############################################
############# Helpers for OOP ###############
#############################################

def _load_image(input_data: Any) -> Image.Image:
    """
    Normalize input into a RGB PIL.Image.Image.

    Accepts:
      - PIL.Image.Image directly
      - str or Path -> treated as a filesystem path
    """
    if isinstance(input_data, Image.Image):
        return input_data.convert("RGB")

    if isinstance(input_data, (str, Path)):
        path = Path(input_data)
        if not path.exists():
            raise FileNotFoundError(f"Image path does not exist: {path}")
        return Image.open(path).convert("RGB")

    raise TypeError(
        f"Unsupported input type {type(input_data)}. "
        "Pass a PIL.Image.Image or a path string/Path."
    )

def _safe_float(val):
    try:
        return float(val)
    except Exception:
        return None

#############################################
############# Main OOP Wrapper ##############
#############################################

class WeatherMind:
    """
    High level interface for running WeatherMind models.

    Usage:
        mind = WeatherMind()
        mind.load_model("QWEN")
        msg = mind.process_input(img)
    """

    def __init__(
        self,
        default_model_name: str = DEFAULT_MODEL_NAME,
        metadata_csv: Optional[str] = None,
        default_context_hours: Optional[float] = None,
    ):
        self.default_model_name = default_model_name.upper()
        self.model: Optional[BaseWeatherModel] = None
        self.current_model_name: Optional[str] = None

        self.metadata_df: Optional[pd.DataFrame] = None
        self.default_context_hours: Optional[float] = default_context_hours
        if metadata_csv is not None:
            self.load_metadata_csv(metadata_csv)

    def load_model(self, model_name: str | None = None) -> None:
        """
        Load and initialize the chosen model.

        Args:
            model_name: Name of the model to load.
                If None, uses self.default_model_name.
        """
        name = (model_name or self.default_model_name).upper()

        assert name in SUPPORTED_MODEL_NAMES, (
            f"Unknown model '{model_name}'. "
            f"Supported: {SUPPORTED_MODEL_NAMES}"
        )

        model_cls = MODEL_REGISTRY[name]
        self.model = model_cls()
        self.current_model_name = name

    def __format_output__(self, raw_output: Any) -> Any:
        """
        Format the model output for presentation.

        Expects raw_output to be a dict with:
          - model_name: str
          - question: str
          - answer: str (whatever the model returned)

        Returns:
          A nicely formatted string ready to print.
        """
        if not isinstance(raw_output, dict):
            return str(raw_output)

        model_name = raw_output.get("model_name", "UNKNOWN")
        question = raw_output.get("question", "")
        answer_raw = raw_output.get("answer", "")

        question = str(question).strip()
        answer_raw = str(answer_raw).strip()

        answer = self._clean_answer_text(answer_raw)
        answer = self._normalize_answer_spacing(answer)

        formatted = (
            f"[{model_name}] Q: {question}\n"
            f"A: {answer}"
        )
        return formatted
    
    def process_input(
        self,
        input_data: Any,
        template: Optional[str] = None,
        use_metadata: bool = True,
        context_hours: Optional[float] = None,
    ) -> Any:
        """
        Run the current model on `input_data` and format the output.

        Args:
            input_data: Image, path, etc.
            template: User question / prompt.
            use_metadata: If True and metadata_df is loaded, prepend weather context.
            context_hours: Size of the time window (in hours) to use for context.
                           If None, uses self.default_context_hours.
                           If still None, only the single row for this image is used.
        """
        if self.model is None:
            self.load_model()

        base_question = template or DEFAULT_TEMPLATE

        effective_context_hours: Optional[float] = (
            context_hours
            if context_hours is not None
            else self.default_context_hours
        )

        context_str: Optional[str] = None
        if use_metadata and self.metadata_df is not None:
            if isinstance(input_data, (str, Path)):
                context_str = self._build_weather_context_for_image(
                    str(input_data),
                    context_hours=effective_context_hours,
                )

        if context_str:
            question = (
                f"{context_str}\n\n"
                "Using both the image and the measurements above, "
                "answer the following question about future or current weather:\n"
                f"{base_question}"
            )
        else:
            question = base_question

        raw_answer = self.model(input_data, question)

        raw_output = {
            "model_name": self.current_model_name or "UNKNOWN",
            "question": base_question,
            "answer": raw_answer,
        }

        formatted_output = self.__format_output__(raw_output)
        return formatted_output


    
    def load_metadata_csv(self, csv_path: str) -> None:
        """
        Load per-image weather metadata from a CSV.

        Expected columns include at least:
            - image_path
            - date, time
            - humidity_pct, temperature_f, feels_like_f
            - pressure_hpa, wind_speed_mph, gust_speed_mph
            - rain_today_in
        """
        df = pd.read_csv(csv_path)

        if "image_path" not in df.columns:
            raise ValueError(
                f"metadata CSV must contain an 'image_path' column. "
                f"Got columns: {df.columns.tolist()}"
            )

        df["image_path"] = df["image_path"].astype(str)

        if "date" in df.columns and "time" in df.columns:
            df["datetime"] = pd.to_datetime(
                df["date"].astype(str) + " " + df["time"].astype(str),
                errors="coerce",
            )

        self.metadata_df = df


    def _build_weather_context_for_image(
        self,
        image_path: str,
        context_hours: Optional[float] = None,
    ) -> Optional[str]:
        """
        Given an image path, look up its row in metadata_df and build a short
        natural-language context string describing weather up to that timestamp.

        If context_hours is None:
            use only the row matching this image.

        If context_hours is a number (e.g. 1, 2, 6):
            use all rows whose datetime is within [t0 - context_hours, t0],
            where t0 is the timestamp of the image row.
        """
        if self.metadata_df is None:
            return None

        df = self.metadata_df

        if "image_path" not in df.columns:
            return None

        img_name = Path(image_path).name

        matches = df[df["image_path"].astype(str).str.endswith(img_name)]
        if matches.empty:
            return None

        anchor_row = matches.iloc[-1]

        use_window = (
            context_hours is not None
            and "datetime" in df.columns
            and pd.notna(anchor_row.get("datetime", pd.NaT))
        )

        if not use_window:
            rows = [anchor_row]
        else:
            t0 = anchor_row["datetime"]
            start_time = t0 - pd.Timedelta(hours=float(context_hours))

            window_df = df.copy()
            window_df = window_df[
                (window_df["datetime"] >= start_time)
                & (window_df["datetime"] <= t0)
            ].sort_values("datetime")

            if window_df.empty:
                rows = [anchor_row]
            else:
                rows = [r for _, r in window_df.iterrows()]

        lines: list[str] = []

        if len(rows) == 1:
            header = "Weather station measurements up to the time of this image:"
        else:
            header = (
                "Weather station measurements for the hours leading up to this image "
                f"(last {context_hours:g} hours):"
            )
        lines.append(header)

        for r in rows:
            if "datetime" in r and pd.notna(r["datetime"]):
                ts_str = str(r["datetime"])
            else:
                date = r.get("date", None)
                time = r.get("time", None)
                bits = []
                if pd.notna(date):
                    bits.append(str(date))
                if pd.notna(time):
                    bits.append(str(time))
                ts_str = " ".join(bits) if bits else "Unknown time"

            row_parts = [f"Time {ts_str}"]

            def add_num_short(label: str, key: str, unit: Optional[str] = None):
                if key not in r:
                    return
                val = r[key]
                if pd.isna(val):
                    return

                v = _safe_float(val)
                if v is None:
                    return
                value_str = f"{v:.1f}"

                if unit:
                    row_parts.append(f"{label}={value_str}{unit}")
                else:
                    row_parts.append(f"{label}={value_str}")

            add_num_short("RH", "humidity_pct", "%")
            add_num_short("T", "temperature_f", "°F")
            add_num_short("T_feels", "feels_like_f", "°F")
            add_num_short("P", "pressure_hpa", " hPa")
            add_num_short("Wind", "wind_speed_mph", " mph")
            add_num_short("Gust", "gust_speed_mph", " mph")
            add_num_short("Rain_today", "rain_today_in", " in")

            lines.append("- " + ", ".join(row_parts))

        context = "\n".join(lines)
        return context



    @staticmethod
    def _clean_answer_text(text: str) -> str:
        """
        Clean model answers that look like chat transcripts, e.g.:

        'User: ...\nAssistant: actual answer'

        Returns only the assistant's final message.
        """
        if not text:
            return text

        if "assistant" in text.lower():
            parts = re.split(r"assistant\s*:\s*", text, flags=re.IGNORECASE)
            if len(parts) >= 2:
                text = parts[-1]

        text = re.sub(r"^user\s*:\s*", "", text, flags=re.IGNORECASE).strip()

        return text
    
    @staticmethod
    def _normalize_answer_spacing(text: str) -> str:
        """
        Remove awkward newlines / blank lines and make the answer a single paragraph.

        Example:
            "No.\n\nThe sky is clear." -> "No. The sky is clear."
        """
        if not text:
            return text

        lines = [line.strip() for line in text.splitlines() if line.strip()]

        normalized = " ".join(lines)
        normalized = " ".join(normalized.split())

        return normalized